Homework/W10D1/capybara_rspec/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  resources :users, only: %i[create new show]
  resource :session, only: %i[create new destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: %i[new index]
end

Homework/W10D1/capybara_rspec/app/controllers/bands_controller.rb
# rubocop:disable all

class BandsController < ApplicationController
  before_action :ensure_logged_in
  
  def index
    render :index
  end

  def show
    @band = Band.find_by(id: params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to bands_url
    end
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def update
    @band = Band.find_by(id: params[:id])
    if @band.update(band_params)
      render :show
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to bands_url
    end
  end

  def destroy
    @band = Band.find_by(id: params[:id])
    @band.delete if @band
    render :index
  end

  private

  def band_params
    params.require(:bands).permit(:name)
  end
end

Homework/W10D1/capybara_rspec/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    # render json: User.find(params[:id])
    redirect_to :bands
   end

  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      flash[:message] = 'Welcome Back'
      # redirect_to user_url(@user)
      redirect_to :bands
      # render :show
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

Homework/W10D1/capybara_rspec/app/views/users/new.html.erb
<h1>Music App</h1>

<h2>New user</h2>

<a href="<%= new_session_url %>">Go to Sign-in</a>

<form action="<%= users_url %>" method = "POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <p>
    <label for="sign_in_email">Email</label>
    <input type="text" name="user[email]" id="sign_in_email">
  </p>
  <p>
    <label for="sign_in_password">Password</label>
    <input type="password" name="user[password]" id="sign_in_password">
  </p>
  <input type="submit" value="Submit">
</form>