Curriculum/03 Rails/W10D4 Advanced Rails Forms/reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i[new create]
  resource :session, only: %i[new create destroy]
  resources :subs, except: %i[destroy]
  resources :posts, except: %i[index destroy] do
    resources :comments, only: %i[new]
  end
  resources :comments, except: %i[new index destroy]
end

Curriculum/03 Rails/W10D4 Advanced Rails Forms/reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <%if flash[:errors] %>
      <% flash[:errors].each do |error|  %>
        <%= error %>  
      <% end %>
      <br>
    <% else %>
      <br>
    <% end %>

    <% if logged_in? %>
      <ul>
        <li><%= current_user.username %></li>
        <li><a href="<%= new_sub_url %>">Create a sub!</a></li>
        <li><a href="<%= subs_url %>">All Subs</a></li>
        <li>
        <form action="<%= session_url %>" method="POST">
          <input type="hidden" name="_method" value="DELETE">
          <input type="hidden"
                 name="authenticity_token"
                value="<%= form_authenticity_token %>">
          <input type="submit" value="Logout">
        </form>
        </li>
      </ul>
    <% else %>
      <a href="<%= new_session_url %>">Sign in!</a><br><br>
    <% end %>

    <%= yield %>
  </body>
</html>